[package]
name = 'gadjidR'
version = '0.0.1'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'gadjidR'

[dependencies]
anyhow = "1.0.79"
extendr-api = '*'
gadjid = { path = "../../../gadjid" }

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
