# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gadjidR_wrappers", use_symbols = TRUE, package_name = "gadjidR")

#' @docType package
#' @usage NULL
#' @useDynLib gadjidR, .registration = TRUE
NULL

#' Parent Adjustment Intervention Distance between two DAG / CPDAG adjacency matrices (dense)
#' @export
parent_aid <- function(true_adjacency, guess_adjacency, edge_direction) .Call(wrap__parent_aid, true_adjacency, guess_adjacency, edge_direction)

#' Ancestor Adjustment Identification Distance between two DAG / CPDAG adjacency matrices (dense)
#' @export
ancestor_aid <- function(true_adjacency, guess_adjacency, edge_direction) .Call(wrap__ancestor_aid, true_adjacency, guess_adjacency, edge_direction)

#' Optimal Adjustment Intervention Distance between two DAG / CPDAG adjacency matrices (dense)
#' @export
oset_aid <- function(true_adjacency, guess_adjacency, edge_direction) .Call(wrap__oset_aid, true_adjacency, guess_adjacency, edge_direction)

#' Structural Intervention Distance between two DAG adjacency matrices (dense)
#' @export
sid <- function(true_adjacency, guess_adjacency, edge_direction) .Call(wrap__sid, true_adjacency, guess_adjacency, edge_direction)

#' Structural Hamming Distance between two DAG / CPDAG adjacency matrices (dense).
#' Does not take `edge_direction` argument, as SHD reads the matrix 1:1.
#' @export
shd <- function(true_adjacency, guess_adjacency) .Call(wrap__shd, true_adjacency, guess_adjacency)

#' Gets the children of the first node, sanity check for row/column major loading
#' @export
children_of_first_node <- function(true_adjacency, edge_direction) .Call(wrap__children_of_first_node, true_adjacency, edge_direction)


# nolint end
