# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rgadjid_wrappers", use_symbols = TRUE, package_name = "rgadjid")

#' @docType package
#' @usage NULL
#' @useDynLib rgadjid, .registration = TRUE
NULL

#' @export
#' Parent Adjustment Intervention Distance between two DAG / CPDAG adjacency matrices (sparse or dense)
parent_aid <- function(true_adjacency, guess_adjacency, edge_semantics) .Call(wrap__parent_aid, true_adjacency, guess_adjacency, edge_semantics)

#' @export
#' Ancestor Adjustment Identification Distance between two DAG / CPDAG adjacency matrices (sparse or dense)
ancestor_aid <- function(true_adjacency, guess_adjacency, edge_semantics) .Call(wrap__ancestor_aid, true_adjacency, guess_adjacency, edge_semantics)

#' @export
#' Optimal Adjustment Intervention Distance between two DAG / CPDAG adjacency matrices (sparse or dense)
oset_aid <- function(true_adjacency, guess_adjacency, edge_semantics) .Call(wrap__oset_aid, true_adjacency, guess_adjacency, edge_semantics)

#' @export
#' Structural Intervention Distance between two DAG adjacency matrices (sparse or dense)
sid <- function(true_adjacency, guess_adjacency, edge_semantics) .Call(wrap__sid, true_adjacency, guess_adjacency, edge_semantics)

#' @export
#' Structural Hamming Distance between two DAG / CPDAG adjacency matrices (sparse or dense)
shd <- function(true_adjacency, guess_adjacency, edge_semantics) .Call(wrap__shd, true_adjacency, guess_adjacency, edge_semantics)

#' @export
#' Gets the children of the first node, sanity check for row/column major loading
children_of_first_node <- function(true_adjacency, edge_semantics) .Call(wrap__children_of_first_node, true_adjacency, edge_semantics)


# nolint end
